global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["monitoring_prometheus:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["monitoring_node-exporter:9100"]
